
GET {{URL}}/sessions
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
###
GET {{URL}}/sessions/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
###
POST {{URL}}/sessions
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "user": {
    "username": "admin",
    "password": "admin123"
  },
  "exercises": []
}

###
PUT {{URL}}/sessions/addExerciseToSession/2/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

###
PUT {{URL}}/api/sessions/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "user": {
    "id": 1,
    "username": "user1",
    "password": "password"
  },
  "exercise": [
    {
      "name": "Test Exercise",
      "description": "TEST",
      "muscleGroup": "ABS",
      "sets": [
        {
          "reps": 15,
          "weight": 0
        }
      ]
    }
  ]
}
###
DELETE {{URL}}/sessions/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{URL}}/exercises
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
###
GET {{URL}}/exercises/3
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
###
POST {{URL}}/exercises
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Test Exercise",
  "description": "TEST",
  "muscleGroup": "ABS"
}
###
PUT {{URL}}/exercises/3
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Test Exercise",
  "description": "TESTUPDATED",
  "muscleGroup": "ABS"
}
###
DELETE {{URL}}/exercises/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
###


POST {{URL}}/auth/login
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

"username": "admin",
"password": "admin123"

}

> {% client.global.set("jwt_token", response.body.token); %}
###
POST {{URL}}/auth/register
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "username": "admin",
  "password": "admin123"
}
###
GET {{URL}}/auth/users
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
###
PUT {{URL}}/auth/users/user1/role
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "role": "ADMIN"
}
###